### ISSUE TITLE
testcloud command needs to be updated

### ISSUE THREAD

**Issue by JohannHilbold** [bitrise-steplib/steps-xamarin-test-cloud-for-calabash-android#7]
Hi there,
It appears that the testcloud command is outdated. I've talked to the guys at Xamarin, they said the following:

Earlier we use the Test Cloud upload command: test-cloud.exe submit <PATH-TO-APK> <TEAM API KEY> --devices=<DEVICES> --assembly-dir=<PATH-TO-TEST-ASSEMBLY-DIR> --user=<EMAIL>
But right now we use the AppCenter Test Upload command: appcenter test run uitest --app "<APP NAME>" --devices "<DEVICE SET NAME>" --app-path <PATH_TO_APK> --test-series "<TEST SERIES>" --locale "en_US" --build-dir <PATH TO UITEST BUILD DIRECTORY> 
inturn it will automatically us the test-cloud.exe back-end.
 Refer the below repo which gives detailed instructions on generating an App Center Test command
https://github.com/King-of-Spades/AppCenter-Test-Samples/

The important part here is that the <TEAM API KEY> is not valid anymore. Therefore the bitrise step as is it today cannot work and will throw "Invalid API key" error.

On the Xamarin side, they've changed their login system, apparently. 
When using the CLI, you log in first using the command "appcenter login"
Only then you can run the "test" command, and without the API keym which makes sense because you are now logged in.

https://docs.microsoft.com/en-us/appcenter/quickstarts/android/test

**Comment by viktorbenei** [comment]
Thanks for reporting @JohannHilbold , we'll check this ASAP! :)

**Comment by godrei** [comment]
Hi we release the [App Center upload and schedule tests](https://github.com/bitrise-steplib/steps-appcenter-test) step.
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
